string hD01="    /\  /\__ _ _ __   __ _ _ __ ___   __ _ _ __  "
string hD02="   / /_/ / _` | '_ \ / _` | '_ ` _ \ / _` | '_ \ "
string hD03="  / __  / (_| | | | | (_| | | | | | | (_| | | | |"
string hD04="  \/ /_/ \__,_|_| |_|\__, |_| |_| |_|\__,_|_| |_|"
string hD05="                     |___/                       "
string hD06="                             by Elliott Plack     "
string hD07="                                                 "
string hD08="      _______                                    "
string hD09="     |/      |             ______________________   "
string hD10="     |      (_)         |                       |  "
string hD11="     |      \|/        | Your Progress        |  "
string hD12="     |       |         |                      |  "
string hD13="     |      / \        |                      |  "
string hD14="     |                    |                      |  "
string hD15="  ___|___                |______________________|  "


string hD01="    /\  /\__ _ _ __   __ _ _ __ ___   __ _ _ __  ";
string hD02="   / /_/ / _` | '_ \ / _` | '_ ` _ \ / _` | '_ \ ";
string hD03="  / __  / (_| | | | | (_| | | | | | | (_| | | | |";
string hD04="  \/ /_/ \__,_|_| |_|\__, |_| |_| |_|\__,_|_| |_|";
string hD05="                     |___/                       ";
string hD06="                            by Elliott Plack     ";
string hD07="                                                 ";
string hD08="      _______                                    ";
string hD09="     |/      |          ______________________   ";
string hD10="     |                 |                      |  ";
string hD11="     |                 | Your Progress        |  ";
string hD12="     |                 |                      |  ";
string hD13="     |                 |                      |  ";
string hD14="     |                 |                      |  ";
string hD15="  ___|___              |______________________|  ";